const DataStore = {
  metrics: [
    { label: 'Total Tests', value: '1,284', sub: '+12 esta semana', class: 'cyan' },
    { label: 'Pass Rate', value: '97.3%', sub: '+0.8% vs. anterior', class: 'green' },
    { label: 'Coverage', value: '84%', sub: '+3% este mês', class: 'green' },
    { label: 'Scenarios', value: '342', sub: '18 automações novas', class: 'yellow' },
  ],

  scenarios: [
    { id: 'SC-001', title: 'Login com credenciais válidas', desc: 'Verifica fluxo completo de autenticação com usuário e senha corretos.', status: 'passed', priority: 'critical', suite: 'Auth' },
    { id: 'SC-002', title: 'Login com senha inválida', desc: 'Valida mensagem de erro ao tentar login com credenciais incorretas.', status: 'passed', priority: 'high', suite: 'Auth' },
    { id: 'SC-003', title: 'Recuperação de senha', desc: 'Fluxo de reset de senha via email com token de recuperação.', status: 'passed', priority: 'high', suite: 'Auth' },
    { id: 'SC-004', title: 'Cadastro de novo usuário', desc: 'Registro com validação de campos obrigatórios e email único.', status: 'passed', priority: 'critical', suite: 'Auth' },
    { id: 'SC-005', title: 'Busca de produtos por termo', desc: 'Pesquisa textual retorna resultados relevantes com timeout < 2s.', status: 'passed', priority: 'high', suite: 'Catalog' },
    { id: 'SC-006', title: 'Filtro por categoria', desc: 'Combinação de filtros de categoria e faixa de preço.', status: 'passed', priority: 'medium', suite: 'Catalog' },
    { id: 'SC-007', title: 'Paginação dos resultados', desc: 'Navegação entre páginas preserva filtros aplicados.', status: 'passed', priority: 'medium', suite: 'Catalog' },
    { id: 'SC-008', title: 'Adicionar item ao carrinho', desc: 'Item é adicionado com quantidade correta e exibe badge no ícone.', status: 'passed', priority: 'critical', suite: 'Cart' },
    { id: 'SC-009', title: 'Remover item do carrinho', desc: 'Remoção atualiza total e badge. Carrinho vazio mostra estado vazio.', status: 'passed', priority: 'high', suite: 'Cart' },
    { id: 'SC-010', title: 'Checkout com cupom de desconto', desc: 'Aplicação de cupom válido altera total e exibe valor corrigido.', status: 'failed', priority: 'critical', suite: 'Checkout' },
    { id: 'SC-011', title: 'Pagamento via cartão de crédito', desc: 'Transação com cartão válido é aprovada e confirmação é exibida.', status: 'passed', priority: 'critical', suite: 'Payment' },
    { id: 'SC-012', title: 'Pagamento com cartão recusado', desc: 'Cartão sem limite exibe mensagem de recusa e sugere outro método.', status: 'passed', priority: 'high', suite: 'Payment' },
    { id: 'SC-013', title: 'Upload de avatar', desc: 'Upload de imagem nos formatos permitidos (jpg, png) até 5MB.', status: 'skipped', priority: 'low', suite: 'Profile' },
    { id: 'SC-014', title: 'Notificações em tempo real', desc: 'WebSocket entrega notificação ao disparar evento no backend.', status: 'passed', priority: 'medium', suite: 'Realtime' },
    { id: 'SC-015', title: 'Timeout na requisição externa', desc: 'API externa com timeout > 10s retorna fallback com dados em cache.', status: 'passed', priority: 'high', suite: 'Resilience' },
    { id: 'SC-016', title: 'Dashboard — carregamento de métricas', desc: 'Gráficos e KPIs da dashboard carregam em menos de 3s.', status: 'passed', priority: 'critical', suite: 'UI' },
    { id: 'SC-017', title: 'Responsividade — mobile (375px)', desc: 'Layout adapta corretamente em viewport 375px sem overflow.', status: 'passed', priority: 'high', suite: 'UI' },
    { id: 'SC-018', title: 'Acessibilidade — contraste de cores', desc: 'Todos os textos atendem AA contrast ratio (4.5:1 mínimo).', status: 'failed', priority: 'high', suite: 'Accessibility' },
    { id: 'SC-019', title: 'Exportação de relatório CSV', desc: 'Relatório de execução é exportado em CSV com dados corretos.', status: 'passed', priority: 'medium', suite: 'Reports' },
    { id: 'SC-020', title: 'Login social — Google OAuth', desc: 'Autenticação via Google retorna à aplicação com sessão criada.', status: 'skipped', priority: 'medium', suite: 'Auth' },
  ],

  history: [
    { run: '#2841', date: '2026-06-20 09:32', status: 'passed', passed: 187, failed: 2, skipped: 5, duration: '4m 12s', branch: 'main' },
    { run: '#2840', date: '2026-06-20 07:15', status: 'passed', passed: 186, failed: 3, skipped: 5, duration: '4m 08s', branch: 'main' },
    { run: '#2839', date: '2026-06-19 22:00', status: 'passed', passed: 185, failed: 3, skipped: 6, duration: '4m 31s', branch: 'main' },
    { run: '#2838', date: '2026-06-19 14:22', status: 'failed', passed: 178, failed: 12, skipped: 4, duration: '4m 55s', branch: 'feat/payment-v2' },
    { run: '#2837', date: '2026-06-19 09:30', status: 'passed', passed: 188, failed: 1, skipped: 5, duration: '4m 02s', branch: 'main' },
    { run: '#2836', date: '2026-06-18 18:45', status: 'passed', passed: 187, failed: 1, skipped: 6, duration: '3m 58s', branch: 'main' },
    { run: '#2835', date: '2026-06-18 11:00', status: 'passed', passed: 186, failed: 2, skipped: 6, duration: '4m 15s', branch: 'main' },
    { run: '#2834', date: '2026-06-17 21:30', status: 'passed', passed: 185, failed: 2, skipped: 7, duration: '4m 22s', branch: 'main' },
    { run: '#2833', date: '2026-06-17 15:10', status: 'failed', passed: 165, failed: 22, skipped: 7, duration: '5m 10s', branch: 'feat/new-catalog' },
    { run: '#2832', date: '2026-06-17 08:00', status: 'passed', passed: 187, failed: 1, skipped: 6, duration: '4m 05s', branch: 'main' },
  ],

  endpoints: [
    { method: 'GET', path: '/api/v2/health', status: 'up', latency: '23ms', lastCheck: '2s ago' },
    { method: 'GET', path: '/api/v2/users', status: 'up', latency: '45ms', lastCheck: '2s ago' },
    { method: 'POST', path: '/api/v2/auth/login', status: 'up', latency: '112ms', lastCheck: '5s ago' },
    { method: 'GET', path: '/api/v2/products', status: 'degraded', latency: '892ms', lastCheck: '10s ago' },
    { method: 'POST', path: '/api/v2/checkout', status: 'up', latency: '234ms', lastCheck: '3s ago' },
    { method: 'GET', path: '/api/v2/orders', status: 'up', latency: '67ms', lastCheck: '2s ago' },
    { method: 'PUT', path: '/api/v2/users/profile', status: 'up', latency: '89ms', lastCheck: '8s ago' },
    { method: 'DELETE', path: '/api/v2/cart/items', status: 'up', latency: '41ms', lastCheck: '4s ago' },
    { method: 'GET', path: '/api/v2/notifications', status: 'down', latency: '—', lastCheck: '30s ago' },
    { method: 'GET', path: '/api/v2/reports/summary', status: 'up', latency: '156ms', lastCheck: '1s ago' },
  ],

  getMetrics() { return this.metrics; },
  getScenarios() { return this.scenarios; },
  getHistory() { return this.history; },
  getEndpoints() { return this.endpoints; },
};
