const DataStore = {
  metrics: [
    { label: 'Total Tests', value: '1,284', sub: '+12 esta semana', class: 'cyan' },
    { label: 'Pass Rate', value: '97.3%', sub: '+0.8% vs. anterior', class: 'green' },
    { label: 'Coverage', value: '84%', sub: '+3% este mês', class: 'green' },
    { label: 'Scenarios', value: '342', sub: '18 automações novas', class: 'yellow' },
  ],

  scenarios: [
    { id: 'SC-001', title: 'Login com credenciais válidas', desc: 'Verifica fluxo completo de autenticação com usuário e senha corretos.', status: 'passed', priority: 'critical', suite: 'Auth' },
    { id: 'SC-002', title: 'Login com senha inválida', desc: 'Valida mensagem de erro ao tentar login com credenciais incorretas.', status: 'passed', priority: 'high', suite: 'Auth' },
    { id: 'SC-003', title: 'Recuperação de senha', desc: 'Fluxo de reset de senha via email com token de recuperação.', status: 'passed', priority: 'high', suite: 'Auth' },
    { id: 'SC-004', title: 'Cadastro de novo usuário', desc: 'Registro com validação de campos obrigatórios e email único.', status: 'passed', priority: 'critical', suite: 'Auth' },
    { id: 'SC-005', title: 'Busca de produtos por termo', desc: 'Pesquisa textual retorna resultados relevantes com timeout < 2s.', status: 'passed', priority: 'high', suite: 'Catalog' },
    { id: 'SC-006', title: 'Filtro por categoria', desc: 'Combinação de filtros de categoria e faixa de preço.', status: 'passed', priority: 'medium', suite: 'Catalog' },
    { id: 'SC-007', title: 'Paginação dos resultados', desc: 'Navegação entre páginas preserva filtros aplicados.', status: 'passed', priority: 'medium', suite: 'Catalog' },
    { id: 'SC-008', title: 'Adicionar item ao carrinho', desc: 'Item é adicionado com quantidade correta e exibe badge no ícone.', status: 'passed', priority: 'critical', suite: 'Cart' },
    { id: 'SC-009', title: 'Remover item do carrinho', desc: 'Remoção atualiza total e badge. Carrinho vazio mostra estado vazio.', status: 'passed', priority: 'high', suite: 'Cart' },
    { id: 'SC-010', title: 'Checkout com cupom de desconto', desc: 'Aplicação de cupom válido altera total e exibe valor corrigido.', status: 'failed', priority: 'critical', suite: 'Checkout' },
    { id: 'SC-011', title: 'Pagamento via cartão de crédito', desc: 'Transação com cartão válido é aprovada e confirmação é exibida.', status: 'passed', priority: 'critical', suite: 'Payment' },
    { id: 'SC-012', title: 'Pagamento com cartão recusado', desc: 'Cartão sem limite exibe mensagem de recusa e sugere outro método.', status: 'passed', priority: 'high', suite: 'Payment' },
    { id: 'SC-013', title: 'Upload de avatar', desc: 'Upload de imagem nos formatos permitidos (jpg, png) até 5MB.', status: 'skipped', priority: 'low', suite: 'Profile' },
    { id: 'SC-014', title: 'Notificações em tempo real', desc: 'WebSocket entrega notificação ao disparar evento no backend.', status: 'passed', priority: 'medium', suite: 'Realtime' },
    { id: 'SC-015', title: 'Timeout na requisição externa', desc: 'API externa com timeout > 10s retorna fallback com dados em cache.', status: 'passed', priority: 'high', suite: 'Resilience' },
    { id: 'SC-016', title: 'Dashboard — carregamento de métricas', desc: 'Gráficos e KPIs da dashboard carregam em menos de 3s.', status: 'passed', priority: 'critical', suite: 'UI' },
    { id: 'SC-017', title: 'Responsividade — mobile (375px)', desc: 'Layout adapta corretamente em viewport 375px sem overflow.', status: 'passed', priority: 'high', suite: 'UI' },
    { id: 'SC-018', title: 'Acessibilidade — contraste de cores', desc: 'Todos os textos atendem AA contrast ratio (4.5:1 mínimo).', status: 'failed', priority: 'high', suite: 'Accessibility' },
    { id: 'SC-019', title: 'Exportação de relatório CSV', desc: 'Relatório de execução é exportado em CSV com dados corretos.', status: 'passed', priority: 'medium', suite: 'Reports' },
    { id: 'SC-020', title: 'Login social — Google OAuth', desc: 'Autenticação via Google retorna à aplicação com sessão criada.', status: 'skipped', priority: 'medium', suite: 'Auth' },
  ],

  history: [
    { run: '#2841', date: '2026-06-20 09:32', status: 'passed', passed: 187, failed: 2, skipped: 5, duration: '4m 12s', branch: 'main' },
    { run: '#2840', date: '2026-06-20 07:15', status: 'passed', passed: 186, failed: 3, skipped: 5, duration: '4m 08s', branch: 'main' },
    { run: '#2839', date: '2026-06-19 22:00', status: 'passed', passed: 185, failed: 3, skipped: 6, duration: '4m 31s', branch: 'main' },
    { run: '#2838', date: '2026-06-19 14:22', status: 'failed', passed: 178, failed: 12, skipped: 4, duration: '4m 55s', branch: 'feat/payment-v2' },
    { run: '#2837', date: '2026-06-19 09:30', status: 'passed', passed: 188, failed: 1, skipped: 5, duration: '4m 02s', branch: 'main' },
    { run: '#2836', date: '2026-06-18 18:45', status: 'passed', passed: 187, failed: 1, skipped: 6, duration: '3m 58s', branch: 'main' },
    { run: '#2835', date: '2026-06-18 11:00', status: 'passed', passed: 186, failed: 2, skipped: 6, duration: '4m 15s', branch: 'main' },
    { run: '#2834', date: '2026-06-17 21:30', status: 'passed', passed: 185, failed: 2, skipped: 7, duration: '4m 22s', branch: 'main' },
    { run: '#2833', date: '2026-06-17 15:10', status: 'failed', passed: 165, failed: 22, skipped: 7, duration: '5m 10s', branch: 'feat/new-catalog' },
    { run: '#2832', date: '2026-06-17 08:00', status: 'passed', passed: 187, failed: 1, skipped: 6, duration: '4m 05s', branch: 'main' },
  ],

  endpoints: [
    { method: 'GET', path: '/api/v2/health', status: 'up', latency: '23ms', lastCheck: '2s ago' },
    { method: 'GET', path: '/api/v2/users', status: 'up', latency: '45ms', lastCheck: '2s ago' },
    { method: 'POST', path: '/api/v2/auth/login', status: 'up', latency: '112ms', lastCheck: '5s ago' },
    { method: 'GET', path: '/api/v2/products', status: 'degraded', latency: '892ms', lastCheck: '10s ago' },
    { method: 'POST', path: '/api/v2/checkout', status: 'up', latency: '234ms', lastCheck: '3s ago' },
    { method: 'GET', path: '/api/v2/orders', status: 'up', latency: '67ms', lastCheck: '2s ago' },
    { method: 'PUT', path: '/api/v2/users/profile', status: 'up', latency: '89ms', lastCheck: '8s ago' },
    { method: 'DELETE', path: '/api/v2/cart/items', status: 'up', latency: '41ms', lastCheck: '4s ago' },
    { method: 'GET', path: '/api/v2/notifications', status: 'down', latency: '—', lastCheck: '30s ago' },
    { method: 'GET', path: '/api/v2/reports/summary', status: 'up', latency: '156ms', lastCheck: '1s ago' },
  ],

  testCases: [
    { id: 'TC-001', title: 'Login with valid credentials', description: 'Verify the full authentication flow using correct username and password.', preconditions: ['User must have an active account with valid credentials', 'Login page must be reachable'], steps: ['Navigate to the login page', 'Enter a valid username in the username input', 'Enter the corresponding password in the password input', 'Click the "Sign In" button'], expectedResult: 'Dashboard loads and a welcome message with the user name is displayed. User remains authenticated across pages.', status: 'passed', priority: 'critical', suite: 'Auth' },
    { id: 'TC-002', title: 'Login with invalid password', description: 'Validate the error handling when an incorrect password is submitted.', preconditions: ['User must be registered', 'Login page must be reachable'], steps: ['Navigate to the login page', 'Enter a valid username', 'Enter an incorrect password', 'Click "Sign In"'], expectedResult: 'An error message "Invalid credentials" appears near the password field. No redirect occurs.', status: 'passed', priority: 'high', suite: 'Auth' },
    { id: 'TC-003', title: 'Recover password via email', description: 'Validate the password recovery flow via registered email.', preconditions: ['User must have a registered email address', 'Login page must be reachable'], steps: ['Navigate to the login page', 'Click "Forgot password?" link', 'Enter the registered email address', 'Click "Send recovery link"', 'Open email and click the recovery link', 'Enter a new password and confirm it'], expectedResult: 'A success toast "Password updated successfully" is shown. User can log in with the new password.', status: 'passed', priority: 'high', suite: 'Auth' },
    { id: 'TC-004', title: 'Register new user with valid data', description: 'Verify that a new user can register with complete and valid information.', preconditions: ['Registration page must be reachable', 'Email must not already be in use'], steps: ['Navigate to the registration page', 'Fill in name, email, password, and confirm password', 'Accept the terms of service', 'Click "Create Account"'], expectedResult: 'Account is created and user is automatically logged in. A welcome email is sent to the provided address.', status: 'passed', priority: 'critical', suite: 'Auth' },
    { id: 'TC-005', title: 'Search products by keyword', description: 'Verify the search functionality returns relevant results quickly.', preconditions: ['Product catalog contains items with varied names'], steps: ['Navigate to the home page', 'Locate the search bar at the top', 'Type a product keyword (e.g. "wireless")', 'Press Enter or click the search icon'], expectedResult: 'A results page loads within 2 seconds showing products that match the keyword. Results display name, price, and image.', status: 'passed', priority: 'high', suite: 'Catalog' },
    { id: 'TC-006', title: 'Filter products by category and price range', description: 'Verify combined filters narrow down the product list correctly.', preconditions: ['Products exist across multiple categories and price ranges'], steps: ['Navigate to the catalog page', 'Select a category from the filter sidebar', 'Set a minimum and maximum price range', 'Click "Apply filters"'], expectedResult: 'Only products matching the selected category and price range are displayed. The result count updates accordingly.', status: 'passed', priority: 'medium', suite: 'Catalog' },
    { id: 'TC-007', title: 'Add single item to cart', description: 'Verify that a single product can be added to the shopping cart.', preconditions: ['Product detail page must be reachable', 'Item must be in stock'], steps: ['Navigate to a product detail page', 'Verify the "Add to Cart" button is enabled', 'Click "Add to Cart"'], expectedResult: 'A confirmation toast "Item added to cart" appears. The cart badge increments by 1.', status: 'passed', priority: 'critical', suite: 'Cart' },
    { id: 'TC-008', title: 'Remove item from cart', description: 'Verify that removing an item updates the cart correctly.', preconditions: ['Cart must contain at least one item'], steps: ['Navigate to the cart page', 'Locate an item in the cart', 'Click the "Remove" or trash icon for that item'], expectedResult: 'Item is removed from the cart list. The total price recalculates. If no items remain, an empty cart message is displayed.', status: 'passed', priority: 'high', suite: 'Cart' },
    { id: 'TC-009', title: 'Apply valid discount coupon', description: 'Verify a valid coupon code is applied and adjusts the total.', preconditions: ['Cart must contain at least one item', 'A valid coupon code must exist'], steps: ['Navigate to the checkout page', 'Locate the coupon code input field', 'Enter a valid coupon code (e.g. "WELCOME10")', 'Click "Apply"'], expectedResult: 'The discount is reflected in the total price. The coupon code appears as applied with the discount amount visible. [Known issue: discount is not always recalculated correctly on bundled items]', status: 'failed', priority: 'critical', suite: 'Checkout' },
    { id: 'TC-010', title: 'Complete checkout with credit card', description: 'Verify the full purchase flow using a valid credit card.', preconditions: ['Cart must contain at least one item', 'User must be logged in', 'Shipping address must be filled'], steps: ['Navigate to checkout', 'Select "Credit Card" as payment method', 'Enter valid card number, expiration date, and CVV', 'Click "Place Order"'], expectedResult: 'Payment is processed. An order confirmation page is displayed with the order number. A confirmation email is sent.', status: 'passed', priority: 'critical', suite: 'Payment' },
    { id: 'TC-011', title: 'Upload profile avatar', description: 'Verify the avatar upload accepts valid image formats.', preconditions: ['User must be logged in', 'Profile settings page must be reachable'], steps: ['Navigate to the profile settings page', 'Click the avatar upload area', 'Select a valid image (JPG or PNG, under 5MB)'], expectedResult: 'Avatar preview updates immediately. A success message "Avatar updated" is shown. The new avatar persists after page refresh.', status: 'skipped', priority: 'low', suite: 'Profile' },
    { id: 'TC-012', title: 'Export report as CSV', description: 'Verify the report export generates a valid CSV file.', preconditions: ['User must be logged in', 'Reports page must have data'], steps: ['Navigate to the reports page', 'Select a date range for the report', 'Click "Export CSV"'], expectedResult: 'A CSV file is downloaded with correct headers and data rows matching the selected range. The file name includes the date.', status: 'passed', priority: 'medium', suite: 'Reports' },
  ],

  bugReports: [
    { id: 'BR-001', title: 'Discount coupon not applied to bundled items', description: 'When a bundled product is in the cart, the discount coupon does not recalculate the total correctly.', severity: 'critical', environment: 'Chrome 125 / Windows 11', stepsToReproduce: ['Add a bundled product (e.g. "Keyboard + Mouse Combo") to cart', 'Navigate to checkout', 'Enter coupon code "WELCOME10" in the discount field', 'Click "Apply"'], actualResult: 'Coupon is accepted but discount is only applied to the first item. Bundle total remains unchanged.', expectedResult: 'Coupon discount should apply to the full bundle price, recalculating the total correctly.', suite: 'Checkout' },
    { id: 'BR-002', title: 'Search results timeout on slow networks', description: 'Product search returns an empty state instead of a loading indicator when the network is slow.', severity: 'high', environment: 'Firefox 126 / macOS 14', stepsToReproduce: ['Open Chrome DevTools and set network to "Slow 3G"', 'Navigate to the catalog page', 'Type "wireless" in the search bar and press Enter'], actualResult: 'Blank empty state displays for 8+ seconds before results appear. No spinner or progress indicator.', expectedResult: 'A loading spinner or skeleton should display while the search request is in progress.', suite: 'Catalog' },
    { id: 'BR-003', title: 'Cart badge count desyncs after removing item', description: 'After removing an item from the cart, the badge count in the header does not update until page refresh.', severity: 'high', environment: 'Chrome 125 / Windows 11', stepsToReproduce: ['Add 3 different items to the cart', 'Observe badge shows "3"', 'Navigate to cart page', 'Remove one item'], actualResult: 'Cart list shows 2 items, but header badge still displays "3". Refreshing the page fixes it.', expectedResult: 'Badge count should update immediately to reflect the current cart item count.', suite: 'Cart' },
    { id: 'BR-004', title: 'Color contrast ratio below AA standard on metric cards', description: 'The metric card labels use a gray (#6b6b6b) on dark (#1c1c1e) background, failing WCAG AA contrast.', severity: 'medium', environment: 'All browsers', stepsToReproduce: ['Open the dashboard page', 'Inspect any metric card label text', 'Measure contrast ratio against the card background'], actualResult: 'Contrast ratio is 3.8:1, below the 4.5:1 minimum required for WCAG AA normal text.', expectedResult: 'Text color should be adjusted to achieve at least 4.5:1 contrast ratio.', suite: 'Accessibility' },
    { id: 'BR-005', title: 'Avatar upload crashes with files over 5MB', description: 'Uploading an image larger than 5MB causes the profile page to crash without an error message.', severity: 'critical', environment: 'Edge 125 / Windows 11', stepsToReproduce: ['Navigate to profile settings', 'Click avatar upload area', 'Select a 6MB JPG file'], actualResult: 'Page becomes unresponsive for 15 seconds, then shows a blank white section where the avatar preview should be.', expectedResult: 'File size validation should reject files over 5MB with a clear error message before uploading.', suite: 'Profile' },
    { id: 'BR-006', title: 'CSV export includes incorrect date column', description: 'The exported CSV report shows the wrong date format and shifts dates by one day.', severity: 'medium', environment: 'Chrome 125 / Windows 11', stepsToReproduce: ['Navigate to reports page', 'Select date range "June 1–June 15, 2026"', 'Click "Export CSV"', 'Open the CSV file in Excel'], actualResult: 'Dates are exported in MM/DD/YYYY format instead of ISO 8601. June 1 appears as May 31 (timezone shift).', expectedResult: 'Dates should be exported in ISO 8601 format (YYYY-MM-DD) with explicit UTC to avoid timezone offset issues.', suite: 'Reports' },
    { id: 'BR-007', title: 'Mobile menu does not close after selecting a link', description: 'On mobile viewport, the navigation menu stays open after tapping a link.', severity: 'high', environment: 'Safari 17 / iOS 17.5', stepsToReproduce: ['Open the site on an iPhone 15 viewport (393px)', 'Tap the menu toggle button', 'Tap any navigation link (e.g. "Dashboard")'], actualResult: 'Page navigates but the menu overlay remains visible, blocking content until manually dismissed.', expectedResult: 'Menu should close automatically after a navigation link is selected.', suite: 'UI' },
    { id: 'BR-008', title: 'Payment confirmation email not sent for approved transactions', description: 'After a successful credit card payment, the confirmation email is not delivered.', severity: 'critical', environment: 'All browsers / Production', stepsToReproduce: ['Complete checkout with a valid credit card', 'Observe order confirmation page with order number', 'Check registered email inbox'], actualResult: 'Order is confirmed on screen, but no confirmation email arrives even after 30 minutes. Spam folder is empty.', expectedResult: 'A confirmation email with order details should be sent within 2 minutes of successful payment.', suite: 'Payment' },
    { id: 'BR-009', title: 'Password recovery link expires before email arrives', description: 'The password recovery link sent via email expires in 5 minutes, but the email often takes 7–10 minutes to arrive.', severity: 'high', environment: 'Gmail / Outlook', stepsToReproduce: ['Click "Forgot password?" on the login page', 'Enter registered email', 'Wait for the recovery email', 'Click the link'], actualResult: 'Link shows "expired or invalid" error. Recovery token TTL is 5 minutes but email delivery is inconsistent.', expectedResult: 'Recovery link TTL should be at least 30 minutes, or email delivery should be improved to arrive within 2 minutes.', suite: 'Auth' },
    { id: 'BR-010', title: 'Filter sidebar collapses when any checkbox is selected on mobile', description: 'On mobile, checking any filter checkbox collapses the entire filter sidebar.', severity: 'medium', environment: 'Chrome 125 / Android 14', stepsToReproduce: ['Open catalog on a 412px viewport', 'Scroll to the filter sidebar', 'Tap any category checkbox (e.g. "Electronics")'], actualResult: 'The entire filter sidebar collapses immediately after the checkbox is checked, hiding the applied filter.', expectedResult: 'Checkbox should remain visible and checked. The sidebar should not collapse on checkbox interaction.', suite: 'Catalog' },
  ],

  statusReport: {
    period: 'Sprint 24-12 (Jun 09 – Jun 20, 2026)',
    readinessScore: 78,
    testSummary: { total: 1284, passed: 1249, failed: 18, skipped: 17 },
    bugSummary: { total: 10, critical: 3, high: 4, medium: 3, low: 0 },
    riskItems: [
      { id: 'RSK-001', description: 'Payment confirmation email delivery intermittent in production', likelihood: 'high', impact: 'critical', status: 'mitigating', owner: 'Platform Team' },
      { id: 'RSK-002', description: 'Bundle discount miscalculation affects 12% of checkout orders', likelihood: 'medium', impact: 'high', status: 'in-progress', owner: 'Checkout Squad' },
      { id: 'RSK-003', description: 'Mobile menu UX regression on iOS Safari 17', likelihood: 'low', impact: 'medium', status: 'resolved', owner: 'UI Team' },
      { id: 'RSK-004', description: 'Password recovery timeout causes 8% drop in reset completion', likelihood: 'high', impact: 'high', status: 'identified', owner: 'Auth Team' },
      { id: 'RSK-005', description: 'CSV export date offset may cause incorrect financial reports', likelihood: 'medium', impact: 'medium', status: 'identified', owner: 'Data Team' },
    ],
    activityLog: [
      { date: '2026-06-20', event: 'Release v2.14.3 deployed to production', type: 'release' },
      { date: '2026-06-19', event: '3 critical bugs triaged in Checkout and Payment suites', type: 'bug' },
      { date: '2026-06-18', event: 'End-to-end regression run completed (284 tests, 97.3% pass)', type: 'test' },
      { date: '2026-06-17', event: 'Performance benchmark: catalog search p95 improved by 320ms', type: 'perf' },
      { date: '2026-06-16', event: 'Security audit: 2 medium findings remediated', type: 'security' },
      { date: '2026-06-13', event: 'Accessibility scan: 4 AA violations fixed across dashboard', type: 'a11y' },
      { date: '2026-06-12', event: 'Bug bash: 14 issues reported, 8 accepted into backlog', type: 'bug' },
      { date: '2026-06-11', event: 'Smoke suite expanded to cover mobile-chrome viewport', type: 'test' },
    ],
  },

  getMetrics() { return this.metrics; },
  getScenarios() { return this.scenarios; },
  getHistory() { return this.history; },
  getEndpoints() { return this.endpoints; },
  getTestCases() { return this.testCases; },
  getBugReports() { return this.bugReports; },
  getStatusReport() { return this.statusReport; },
};
